import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "../components/Footer";
import { GoogleTagManager } from "@next/third-parties/google";
import HeaderNew from "@/components/HeaderNew";
import { CartDataProvider } from "@/utils/contex-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CartDataProvider>
        <body className={`${inter.className}`}>
          <main className="flex w-full flex-col overflow-auto">
            <GoogleTagManager gtmId="GTM-TJG8XG78" />
            {/* <Header /> */}
            <HeaderNew />
            <div className="mt-[80px]">{children}</div>
            <Footer />
          </main>
        </body>
      </CartDataProvider>
    </html>
  );
}
