import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { GoogleTagManager } from "@next/third-parties/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} "testing"`}>
        <main className="flex flex-col w-full h-full overflow-auto">
          <GoogleTagManager gtmId="GTM-TJG8XG78" />
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
